# Nama workflow ini yang akan muncul di tab "Actions" di GitHub Anda
name: Publish Docker Image

# Event yang akan memicu workflow ini
on:
  push:
    # Workflow akan berjalan ketika ada push ke branch 'master'
    branches:
      - master
    # Opsional: Jika Anda ingin memicu secara manual dari GitHub UI
    # workflow_dispatch:

# Definisi pekerjaan (jobs) yang akan dijalankan
jobs:
  # Nama job ini, bisa diganti sesuai keinginan
  build-and-publish:
    # Runner yang akan menjalankan job ini
    runs-on: ubuntu-latest

    # Langkah-langkah (steps) yang akan dieksekusi
    steps:
      # Langkah 1: Checkout kode dari repositori GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Langkah 3: Ekstrak metadata image (tags dan labels) dari Git
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: andhitr/php-contact-app # Ganti dengan nama image Anda di Docker Hub
          tags: |
            type=raw,value=latest,enable=true # Selalu tag sebagai 'latest'
            type=sha,enable=true # Tag dengan SHA commit penuh (misal: 12345abcdef)
            type=ref,event=branch,enable=true # Tag dengan nama branch (misal: master)
            # Anda bisa menambahkan tag lain jika diperlukan, misalnya versi aplikasi
            # type=semver,pattern={{version}} # Jika Anda menggunakan semantic versioning di Git tags

      # Langkah 4: Build dan Push image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
